### ISSUE TITLE
What is the best way to handle multiple CloudFront distribution ids?

### ISSUE THREAD

**Issue by iphoting** [dlapiduz/certbot-s3front#19]
Hello,

Let's say I have a single LE cert with multiple domains (specified with multiple `-d`) and would like to apply the same cert to _multiple_ CloudFront Distributions (because they each serve from different S3 buckets).

What is the most efficient way to do it?

Run the command in a loop with the same command line arguments, except for the different `cf-distribution-id`?

**Comment by dlapiduz** [comment]
So, I haven't tried this but I am pretty sure it would work:
What you can do is create the certificate fist with the `certonly` command and then install it into multiple distributions. In fact if you try to get the same certificate you might get the prompt to just install it.

Plz let me know if that works out.

**Comment by iphoting** [comment]
Great idea, I'll give it a go once there's persistence to Dan's [lambda code][1].

[1]: https://vittegleo.com/blog/letsencrypt-lambda-function/

**Comment by iphoting** [comment]
Taking a step back and thinking about the initial `certonly` step of the certification generation with multiple `-d` values, given that each different domain is served by a different S3 bucket, do you think that `s3front:auth` can be used to automate the validation process?

Am I right to say that given the current code, it's unlikely to be possible?

**Comment by dlapiduz** [comment]
@iphoting yes it'd require some code changes to do that...
