### ISSUE TITLE
Weird error messages, but the certificates are working

### ISSUE THREAD

**Issue by rene-pxl** [dlapiduz/certbot-s3front#34]
Hey (this is my first posted issue on github and im not sure whether to post it here or not),

i've used this plugin to create a multidomain cert request, looking like this :
`AWS_ACCESS_KEY_ID="myaccesskey" AWS_SECRET_ACCESS_KEY="mysecretkey" letsencrypt --agree-tos -a letsencrypt-s3front:auth --letsencrypt-s3front:auth-s3-bucket my.s3bucket.com --letsencrypt-s3front:auth-s3-region eu-west-1  -i letsencrypt-s3front:installer --letsencrypt-s3front:installer-cf-distribution-id mycfdistribution -d ms0.example.com -d ms1.example.com -d ms2.example.com -d ms3.example.com -d ms4.example.com -d ms5.example.com -d ms6.example.com -d ms7.example.com -d ms8.example.com -d ms9.example.com` (im using real values, just removed the credentials and domain info)

I had to give an e-mail adress for the lost key recovery and information mails, which was also okay, then the request was in process and i got the message that an error occured, so i took a look into the /var/log/letsencrypt/letsencrypt.log
`2016-05-26 11:27:22,292:DEBUG:botocore.parsers:Response body:
<?xml version="1.0"?>
<ErrorResponse xmlns="http://cloudfront.amazonaws.com/doc/2016-01-28/"><Error><Type>Sender</Type><Code>IllegalUpdate</Code><Message>Only one viewer certificate change may be in progress at a time.</Message></Error><RequestId>cfa99dee-2334-11e6-b3be-f141091894dc</RequestId></ErrorResponse>
2016-05-26 11:27:22,292:DEBUG:botocore.hooks:Event needs-retry.cloudfront.UpdateDistribution: calling handler <botocore.retryhandler.RetryHandler object at 0x7f728a7d0610>
2016-05-26 11:27:22,292:DEBUG:botocore.retryhandler:No retry needed.
2016-05-26 11:27:22,293:DEBUG:certbot.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/certbot/client.py", line 361, in deploy_certificate
    fullchain_path=fullchain_path)
  File "/usr/local/lib/python2.7/dist-packages/letsencrypt_s3front/installer.py", line 87, in deploy_cert
    IfMatch=cf_cfg['ETag'])
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 258, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 548, in _make_api_call
    raise ClientError(parsed_response, operation_name)
ClientError: An error occurred (IllegalUpdate) when calling the UpdateDistribution operation: Only one viewer certificate change may be in progress at a time.`

I was kinda confused because i took a peek into CloudFront Console and saw that my distribution was processing and i had the option to chose between two custom ssl certificates (le-ms0.example.com and le-ms1.example.com-new). I didn't take any action, so right now it is using 'le-ms0.example.com' and all cnames are using a valid ssl certificate. I wasn't really concerned as it was working (yeah, stupid attitude) but when i added the '--renew-by-default --text' to the call to renew the certificate, it was giving me following error : 
`2016-06-03 06:52:28,966:DEBUG:botocore.endpoint:Sending http request: <PreparedRequest [POST]>
2016-06-03 06:52:28,966:INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): iam.amazonaws.com
2016-06-03 06:52:29,313:DEBUG:botocore.vendored.requests.packages.urllib3.connectionpool:"POST / HTTP/1.1" 409 325
2016-06-03 06:52:29,314:DEBUG:botocore.parsers:Response headers: {'x-amzn-requestid': 'b8648e76-2957-11e6-8268-b3e3c27ca740', 'date': 'Fri, 03 Jun 2016 06:52:20 GMT', 'content-length': '325', 'content-type': 'text/xml'}
2016-06-03 06:52:29,314:DEBUG:botocore.parsers:Response body:`
`<ErrorResponse xmlns="https://iam.amazonaws.com/doc/2010-05-08/">
  <Error>
    <Type>Sender</Type>
    <Code>EntityAlreadyExists</Code>
    <Message>The Server Certificate with name le-ms1.example.com-new already exists.</Message>
  </Error>
  <RequestId>b8648e76-2957-11e6-8268-b3e3c27ca740</RequestId>
</ErrorResponse>`

`2016-06-03 06:52:29,314:DEBUG:botocore.hooks:Event needs-retry.iam.UploadServerCertificate: calling handler <botocore.retryhandler.RetryHandler object at 0x7f44d46db9d0>
2016-06-03 06:52:29,314:DEBUG:botocore.retryhandler:No retry needed.
2016-06-03 06:52:29,315:DEBUG:botocore.hooks:Event after-call.iam.UploadServerCertificate: calling handler <function json_decode_policies at 0x7f44d8fb98c0>
2016-06-03 06:52:29,315:DEBUG:certbot.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/certbot/client.py", line 361, in deploy_certificate
    fullchain_path=fullchain_path)
  File "/usr/local/lib/python2.7/dist-packages/letsencrypt_s3front/installer.py", line 67, in deploy_cert
    CertificateChain=chain
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 258, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 548, in _make_api_call
    raise ClientError(parsed_response, operation_name)
ClientError: An error occurred (EntityAlreadyExists) when calling the UploadServerCertificate operation: The Server Certificate with name le-ms1.example.com-new already exists.`

Still, the cloudfront distribution was starting to process but the date the certificate expires didn't change.

As is this issue wasn't that time critical (still around 85 days left with a valid, working certificate), i decided to wait some days and when i checked the certificate today, there were 7 days added to the certificate expiry date.
Im kinda confused as i wanted to chain the renew call with a deadmanssnitch call but with an error in the renew call, the cronjob is not firing the call to deadmanssnitch.

What am i missing? 
Your help is greatly appreciated.

best regards,
René

**Comment by aripringle** [comment]
@rene-pxl I believe you're running into an issue where specifying multiple domain names causes multiple certificates to be unnecessarily uploaded to IAM/CloudFront. It's unresolved at the moment, although I commented on #31 regarding the issue.

Also, for what it's worth, once you get "stuck" in this situation, you probably need to delete the "le-ms1.example.com-new" certificate manually, or else the renewals won't work. This can be done using the AWS CLI:
`aws iam delete-server-certificate --server-certificate-name le-ms1.example.com-new`

**Comment by rene-pxl** [comment]
@aripringle 
Thanks for your reply.
Yeah that's what i thought as well. 
So far i never needed to manually delete any certificates, it still worked to renew the certificates (for all domains, not only for one or specific ones).
I will try to keep on eye on updates and fixes and in case i need to, use your CLI command.

best regards,
rené

**Comment by dlapiduz** [comment]
@rene-pxl I think the issue is solved now but please let me know if you see it again.

**Comment by ilarischeinin** [comment]
I just ran into this issue. I wanted to create a cert that includes `domain.com`, `www.domain.com`, and `cdn.domain.com`. This resulted in an attempt to install the same certificate multiple times, and the error message mentioned above. (I used only the installer part of s3front and webroot for the authenticator, as I'm using CloudFront as a CDN for a WordPress site via W3 Total Cache.)

As a workaround, I generated one certificate (with multiple names) that is kept local, and another one for only `cdn.domain.com` that gets installed on AWS. This works, but it would be great if I only needed one certificate.

My certbot is version 0.9.3 (on Debian from jessie-backports) and s3front installed via pip seems to be 0.2.0.

**Comment by weierophinney** [comment]
I'm running into this issue as well, with three domains. In each case, I get an error that looks like this:

```text
Starting new HTTPS connection (1): iam.amazonaws.com
An unexpected error occurred:
ClientError: An error occurred (EntityAlreadyExists) when calling the UploadServerCertificate operation: The Server Certificate with name le-<domain-name>-new already exists.
```

When I look in `/var/log/letsencrypt/letsencrypt.log`, I don't really get much more information than that; it shows the request sent, and the response received, which provides that same information.

I've seen some suggestions to use this:

```bash
$ aws iam delete-server-certificate --server-certificate-name le-<domain-name>-new
```

Which I have tried. However, the response I get back is "Certificate <some identifier> is currently inuse by CloudFront Distribution <distribution identifer>. Please remove it first before deleting it from IAM."

These errors have only started in the last two weeks, and I've been able to reproduce them reliably. I'm currently using certbot from thePPA, which installs 0.11.1; I've installed certbot-s3front using pip2.7 (which I discovered through trial and error is necessary, as it does not work with python3), and have 0.2.0 installed.

Any assistance would be greatly appreciated!

**Comment by rene-pxl** [comment]
@dlapiduz 
Sorry to open this again, in the same time frame @weierophinney mentioned, the whole thing stopped working for me as well.
Maybe AWS changed something on their site? Because i didn't change anything at all, in fact i did set up a Cronjob since my last post in this issue and it worked until end of february.

The creation of the certificate itself is still correct, as shown in the log
`2017-04-27 11:53:11,458:INFO:certbot.reporter:Reporting to user: Congratulations! Your certificate and chain have been saved at /etc/letsencrypt/live/ms0.DOMAIN.com/fullchain.pem. Your cert will expire on 2017-07-26. To obtain a new version of the certificate in the future, simply run Certbot again.`

At the end of the log i get this message again 
`ClientError: An error occurred (EntityAlreadyExists) when calling the UploadServerCertificate operation: The Server Certificate with name le-ms0.DOMAIN.com-new already exists.`

This is basically the same message i got in the initial post in this issue BUT this time its not working at anymore.

I can only repeat what @weierophinney said, 

> Any assistance would be greatly appreciated!

**Comment by SystemDisc** [comment]
This still happens.
