### ISSUE TITLE
Python Dialog requirements

### ISSUE THREAD

**Issue by sebastibe** [dlapiduz/certbot-s3front#38]
On Mac OS I was required to install the `dialog` utility for it to work. It could be useful to add it to the README:

``` bash
brew install dialog
```

**Comment by obihann** [comment]
I was just trying to figure this out, thanks for the tip!

**Comment by dlapiduz** [comment]
@sebastibe @obihann for some reason I never had to use it... I wonder where the requirement is coming from...

**Comment by dlapiduz** [comment]
Ok, found it and added it to the README.

Thanks!
