### ISSUE TITLE
creating multiple certificates for different cloudfront ids

### ISSUE THREAD

**Issue by davejfranco** [dlapiduz/certbot-s3front#40]
I'm trying to add another subdomain, which is using a different cloudfront distribution and a different s3 bucket but for some reason certbot is trying to compare the new subdomain with the one I already have so I returns and error like:

`Unable to reach                                                      │  
                                      │ http://stage.talkcenter.io/.well-known/acme-challenge/8N3XE70-11f8HT │  
                                      │ ojRpPv_kmaI2JLYjXwGutoiroalJw: hostname 'stage.talkcenter.io'        │  
                                      │ doesn't match 'app.talkcenter.io'                                    │  
                                      │ Self-verify of challenge failed, authorization abandoned! ` 

Can you help me on this?

**Comment by dlapiduz** [comment]
Hi @davejfranco, this only supports one distribution at a time.

Sorry for the delay BTW!
