### ISSUE TITLE
Not working with certbot python3 version

### ISSUE THREAD

**Issue by elvisangelaccio** [dlapiduz/certbot-s3front#56]
It seems certbot is using python3 nowadays, while certbot-s3front still requires python2 (and installs its files in `/usr/lib/python2.7/site-packages/`). This is what causes #55 

Is certbot-s3front supposed to work with python3?

**Comment by elvisangelaccio** [comment]
This is the backtrace I get if I try to use python3:

```
2017-06-28 17:42:58,315:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.15.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python3.6/site-packages/certbot/main.py", line 723, in main
    plugins = plugins_disco.PluginsRegistry.find_all()
  File "/usr/lib/python3.6/site-packages/certbot/plugins/disco.py", line 200, in find_all
    plugin_ep = PluginEntryPoint(entry_point)
  File "/usr/lib/python3.6/site-packages/certbot/plugins/disco.py", line 47, in __init__
    self.plugin_cls = entry_point.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2303, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2309, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/certbot_s3front/authenticator.py", line 20, in <module>
    class Authenticator(common.Plugin):
  File "/usr/lib/python3.6/site-packages/certbot_s3front/authenticator.py", line 21, in Authenticator
    zope.interface.implements(interfaces.IAuthenticator)
  File "/usr/lib/python3.6/site-packages/zope/interface/declarations.py", line 483, in implements
    raise TypeError(_ADVICE_ERROR % 'implementer')
TypeError: Class advice impossible in Python3.  Use the @implementer class decorator instead.
```

**Comment by agis** [comment]
I'm also bitten by this. Any suggestions?

**Comment by elvisangelaccio** [comment]
@agis As workaround you can create a python2 virtualenv and install certbot/certbot-s3front there.

**Comment by agis** [comment]
@elvisangelaccio Could you please elaborate a bit on this since I'm not familiar with python at all? I've installed virtualenv and did a `virtualenv --python=/usr/bin/python2 certbot-s3front-virtualenv` and then activated this env. But after I run the update script it still throws the error.

**Comment by Ornithologist** [comment]
I have created a python2 virtualenv and installed certbot and certbot-s3front in it.

However when I run certbot I still get a python3 related problem:
```
(venv) ➜  letsencrypt certbot --help
An unexpected error occurred:
TypeError: Class advice impossible in Python3.  Use the @implementer class decorator instead.
Please see the logfile '/var/folders/kx/w2r123xx46jbcq7mhkcs4m1r0000gn/T/tmpas0vjp57' for more details.
```

**Comment by Svolentin** [comment]
same with python 3.6.3
also requirements pins exact versions of zope.*

**Comment by ayox** [comment]
I managed to find a solution for this without a virtual enviorment. 

- You need to uninstall the previous certbot
`sudo pip uninstall certbot-s3front
sudo pip uninstall certbot`
- Make sure there's no other installtion of certbot on your system
`cat $(which certbot) | head -1 ` 
- if you have python 2 installed in your system you can use this command to make sure that certbot runs only with python 2 
`sudo python -m pip install certbot `
`sudo python -m pip install certbot-s3front`

**Comment by dlapiduz** [comment]
This should be fixed now with the version 0.4.0. Please try it and let me know if it works!

**Comment by elvisangelaccio** [comment]
@dlapiduz Is 0.4.0 available on pip yet?

**Comment by dlapiduz** [comment]
@elvisangelaccio  oops, there was an issue with pypi and the CI system didn't notify me. It is up now.
