### ISSUE TITLE
Unrecognized arguments

### ISSUE THREAD

**Issue by jetoneza** [dlapiduz/certbot-s3front#57]
Got this error:

```
$ cat upload-ssl-s3.sh
#!/bin/bash

source /home/foo/.local/share/letsencrypt/bin/activate

AWS_ACCESS_KEY_ID=XXX \
AWS_SECRET_ACCESS_KEY=XXX \
certbot --agree-tos -a certbot-s3front:auth \
--certbot-s3front:auth-s3-bucket XXX \
--certbot-s3front:auth-s3-region us-east-1 \
-i certbot-s3front:installer \
--certbot-s3front:installer-cf-distribution-id XXX \
-d mydomain.com

$ bash upload-ssl-s3.sh
usage:
  letsencrypt-auto [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...

Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
certificate.
certbot: error: unrecognized arguments: --certbot-s3front:auth-s3-bucket XXX --certbot-s3front:auth-s3-region us-east-1 --certbot-s3front:installer-cf-distribution-id XXX
```

Any ideas?

**Comment by dirkcuys** [comment]
@jetoneza I had the same problem, turned out I didn't actually have the plugin installed.

To check if you have the plugin installed, run `certbot plugins`, output should include:

    * certbot-s3front:auth
    Description: S3/CloudFront Authenticator
    Interfaces: IAuthenticator, IPlugin
    Entry point: auth = certbot_s3front.authenticator:Authenticator

**Comment by jetoneza** [comment]
@dirkcuys We switched to AWS Certificate Manager but we will still try this. Thanks!

**Comment by atlemagnussen** [comment]
I also have this issue. Probably because I need to run certbot as sudo in ubuntu 16.04, and I can't install this plugin as sudo.
so "sudo certbot plugins" does not list the plugin

**Comment by dirkcuys** [comment]
You can also install certbot and the plugin in a virtual invironment, then
just run the commands with the absolute path eg. `/opt/venv/bin/pip install
certbot-s3front` and `/opt/venv/bin/certbot ...`

**Comment by dirkcuys** [comment]
You can also install certbot and the plugin in a virtual invironment, then
just run the commands with the absolute path eg. `/opt/venv/bin/pip install
certbot-s3front` and `/opt/venv/bin/certbot ...`

**Comment by mehiatt** [comment]
I am also getting this error. The plugins are installed. Anyone fix this?
