### ISSUE TITLE
How to Install the certificate for second time without prompts

### ISSUE THREAD

**Issue by vladejs** [dlapiduz/certbot-s3front#62]
Hello, I created a cert for a cloudfront distribution, when uploading it gave me error installing it due to an AWS restriction.

Now, the certificate exists, and when I run the command again, it ask me either to install it again (option 1) or renew it (option 2).

How do I tell it to install it again without prompts?

**Comment by dlapiduz** [comment]
Hi @vladejs, You can try using `certbot renew` or using one of the automation options. How are you running this?
