### ISSUE TITLE
Error while running on mac: Self-verify of challenge failed, authorization abandoned!

### ISSUE THREAD

**Issue by mjc0608** [dlapiduz/certbot-s3front#65]
$ cat run_certbot.sh
#!/bin/bash

AWS_ACCESS_KEY_ID="`<<REMOVED>>`" \
AWS_SECRET_ACCESS_KEY="`<<REMOVED>>`" \
certbot --agree-tos -a certbot-s3front:auth \
--certbot-s3front:auth-s3-bucket `<<REMOVED>>` \
--certbot-s3front:auth-s3-region us-east-1 \
--certbot-s3front:auth-s3-directory "" \
-i certbot-s3front:installer \
--certbot-s3front:installer-cf-distribution-id `<<REMOVED>>` \
-d `<<REMOVED>>` -d `<<REMOVED>>`

$ sudo ./run_certbot.sh
Password:
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator certbot-s3front:auth, Installer certbot-s3front:installer
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for `<<REMOVED>>`
http-01 challenge for `<<REMOVED>>`
Found credentials in environment variables.
Starting new HTTPS connection (1): s3.amazonaws.com
Self-verify of challenge failed, authorization abandoned!
Starting new HTTPS connection (1): s3.amazonaws.com
Waiting for verification...
Cleaning up challenges
Starting new HTTPS connection (1): s3.amazonaws.com
Incomplete authorizations

**Comment by iainbryson** [comment]
I'm seeing the same thing on first request.

**Comment by iainbryson** [comment]
Well, if anyone is looking at this I figured out what my issue was: Hover domain forwarding evidently wraps each page in an `iframe`.  That's what the error is; the challenge isn't what was expected or uploaded, it's just an iframe pointing to the .well-known/... challenge in the s3 bucket.
