### ISSUE TITLE
Max retries exceeded with url

### ISSUE THREAD

**Issue by themeaningofmeaning** [dlapiduz/certbot-s3front#71]
Everything has been working great up until my most recent renewal of certificate.  I am getting this error:

Unable to reach http://xxx.com/.well-known/acme-challenge/XXXXXX: HTTPSConnectionPool(host='gigkarma.com', port=443): Max retries exceeded with url: /.well-known/acme-challenge/XXXXXX (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
Self-verify of challenge failed, authorization abandoned!

I should note that our site's current letsencrypt certificate is now expired, but our S3 + Cloudfront confirmation has not changed at all.  The is is the first time that renewing the certificate using certbot-s3front is returning an error.  Any ideas on how to resolve this?

**Comment by rikochet** [comment]
@themeaningofmeaning did you find a solution to this issue?

**Comment by dlapiduz** [comment]
@rikochet are you still seeing this issue?

**Comment by rikochet** [comment]
@dlapiduz I was using certbot-s3front in a production environment and couldn't wait for a fix so I have replaced the LE certs with AWS certs. Would love to use this project again in the future but AWS certs are working for me for now.. Thanks.
